import Link from 'next/link'
import { MessageCircle, Mail, CheckCircle, Wrench, AlertTriangle, MapPin, ChevronRight, ShieldCheck } from 'lucide-react'
import WhatsappCTA from '../../../components/WhatsappCTA'
import LangSwitcher from '../../../components/LangSwitcher'

export const metadata = {
  title: 'Alat Ganti Massey Ferguson Malaysia — Perolehan Alat Ganti Perkins | SourceSage',
  description: 'Pembekal alat ganti traktor Massey Ferguson Malaysia. Seal transmisi, komponen stereng, alat ganti enjin untuk model MF. Perolehan apabila pengedar tunggal kehabisan stok.',
  alternates: { canonical: '/ms/massey-ferguson-parts-malaysia/', languages: { 'en': 'https://sourcesage.ai/massey-ferguson-parts-malaysia/', 'ms': 'https://sourcesage.ai/ms/massey-ferguson-parts-malaysia/', 'zh-Hans': 'https://sourcesage.ai/zh/massey-ferguson-parts-malaysia/', 'x-default': 'https://sourcesage.ai/massey-ferguson-parts-malaysia/' } },
  openGraph: {
    title: 'Alat Ganti Massey Ferguson Malaysia — Perolehan Alat Ganti Perkins | SourceSage',
    description: 'Pembekal alat ganti traktor Massey Ferguson Malaysia. Seal transmisi, komponen stereng, alat ganti enjin untuk model MF. Perolehan apabila pengedar tunggal kehabisan stok.',
    url: 'https://sourcesage.ai/ms/massey-ferguson-parts-malaysia/',
    siteName: 'SourceSage.ai', type: 'website', locale: 'ms_MY',
    images: [{ url: 'https://sourcesage.ai/images/og-home.png', width: 1200, height: 630, alt: 'Alat Ganti Massey Ferguson Malaysia — SourceSage' }],
  },
  twitter: { card: 'summary_large_image', title: 'Alat Ganti Massey Ferguson Malaysia — Perolehan Alat Ganti Perkins | SourceSage', description: 'Pembekal alat ganti traktor Massey Ferguson Malaysia. Seal transmisi, komponen stereng, alat ganti enjin.', images: ['https://sourcesage.ai/images/og-home.png'] },
}

const MODELS = [
  { model: 'MF 240', engine: 'Perkins A4.248 / AD3.152', note: 'Paling biasa di sawah & ladang Malaysia' },
  { model: 'MF 350', engine: 'Perkins A4.248', note: 'Traktor sederhana, meluas di Kedah & Perak' },
  { model: 'MF 375', engine: 'Perkins A4.248 / AD4.203', note: 'Traktor ladang popular' },
  { model: 'MF 385', engine: 'Perkins AD4.203 Turbo', note: 'Kegunaan ladang berat & tanaman baris' },
  { model: 'MF 390', engine: 'Perkins AD4.203 Turbo', note: 'Model eksport, kukuh di Malaysia Timur' },
  { model: 'MF 135 / MF 165', engine: 'Perkins AD3.152', note: 'Model klasik — alat ganti semakin sukar diperoleh' },
]

const PARTS = [
  { category: 'Enjin Perkins', items: ['Kit overhaul / bina semula penuh', 'Kepala silinder (kosong atau dipasang)', 'Muncung penyuntik & pam', 'Pam air & termostat', 'Gasket kepala & set gasket penuh'] },
  { category: 'Transmisi', items: ['Plat klac & plat tekanan', 'Seal aci PTO & galas', 'Garpu pemilih gear', 'Seal minyak pacuan akhir', 'Komponen kunci pembeza'] },
  { category: 'Hidraulik', items: ['Seal lengan angkat & silinder ram', 'Pam hidraulik', 'Pautan atas & alat ganti kawalan draf', 'Elemen penapis & O-ring', 'Injap pelega'] },
  { category: 'Stereng & Gandar', items: ['Seal silinder stereng', 'Kit raja pin & bush', 'Pin pangsi gandar hadapan', 'Set galas roda', 'Hujung rod stereng'] },
  { category: 'Elektrik', items: ['Motor penghidup (12V)', 'Alternator', 'Palam pijar (siri AD)', 'Penghantar suhu & tekanan minyak', 'Panel instrumen'] },
  { category: 'Penapis & Servis', items: ['Penapis minyak enjin', 'Penapis bahan api primer & sekunder', 'Penapis udara & pra-pembersih', 'Penapis balik hidraulik', 'Tali sawat enjin Perkins'] },
]

const FAQS = [
  { q: 'Kenapa alat ganti Massey Ferguson sukar ditemui di Malaysia?', a: 'AGCO (induk MF) mempunyai kehadiran pengedar sah yang terhad di Malaysia berbanding Kubota atau Yanmar. Banyak traktor MF dijual melalui skim pertanian pada 1980-an–2000-an dan rantaian bekalan alat ganti tidak pernah berkembang sepenuhnya. Pengedar yang sedia ada sering memberi tumpuan kepada model baru dan tidak menyimpan stok untuk mesin MF240 atau MF135 lama.' },
  { q: 'Enjin Perkins mana yang digunakan oleh traktor MF saya?', a: 'MF240 dan MF350 paling biasa menggunakan Perkins A4.248 (4-silinder tanpa turbo). MF375 dan MF385 biasanya menggunakan AD4.203 (turbo). MF135 menggunakan AD3.152 (3-silinder). Sentiasa sahkan dari plat enjin — sesetengah traktor MF pasaran eksport menggunakan varian enjin berbeza.' },
  { q: 'Bolehkah anda dapatkan alat ganti untuk traktor MF lama (MF135, MF165)?', a: 'Ya — ini dalam skop kami. Perkins AD3.152 dan A4.212 yang digunakan dalam mesin MF klasik mempunyai ekosistem aftermarket yang besar. Kit overhaul, kepala silinder, dan pam suntikan untuk enjin ini boleh diperoleh — walaupun masa utama dari UK atau India mungkin terpakai.' },
  { q: 'Berapa lama masa yang diambil untuk perolehan?', a: 'Alat ganti MF240/MF350 biasa (penapis, seal, klac) selalunya tersedia di Malaysia dan dihantar dalam 1–3 hari. Kit overhaul enjin dan pam suntikan untuk model lama biasanya mengambil 7–14 hari dari UK, India, atau Singapura. Kami mengesahkan ketersediaan dan ETA sebelum anda komited.' },
  { q: 'Adakah anda membekalkan alat ganti OEM AGCO atau aftermarket?', a: 'Kedua-duanya. Alat ganti OEM AGCO / Perkins mempunyai kebolehkesanan penuh. Aftermarket berkualiti dari jenama terkenal (Sparex, setara David Brown Tractor Parts, kit Perkins buatan India) dilabel dengan jelas dan jauh lebih murah. Banyak bengkel Malaysia beroperasi secara eksklusif dengan aftermarket berkualiti dengan hasil yang cemerlang.' },
]

export default function MsMasseyFergusonPage() {
  const serviceSchema = { '@context': 'https://schema.org', '@type': 'Service', 'inLanguage': 'ms', name: 'Perolehan Alat Ganti Massey Ferguson Malaysia', provider: { '@type': 'LocalBusiness', name: 'SourceSage.ai', url: 'https://sourcesage.ai', areaServed: { '@type': 'Country', name: 'Malaysia' } }, description: 'Perolehan alat ganti traktor Massey Ferguson sukar dicari dengan enjin Perkins di seluruh Malaysia.', serviceType: 'Perolehan Alat Ganti', areaServed: [{ '@type': 'State', name: 'Kedah' }, { '@type': 'State', name: 'Kelantan' }, { '@type': 'State', name: 'Perak' }, { '@type': 'State', name: 'Selangor' }, { '@type': 'State', name: 'Johor' }, { '@type': 'State', name: 'Sabah' }, { '@type': 'State', name: 'Sarawak' }] }
  const breadcrumbSchema = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', 'inLanguage': 'ms', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Laman Utama', item: 'https://sourcesage.ai/ms/' }, { '@type': 'ListItem', position: 2, name: 'Alat Ganti Massey Ferguson Malaysia', item: 'https://sourcesage.ai/ms/massey-ferguson-parts-malaysia' }] }
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', 'inLanguage': 'ms', mainEntity: FAQS.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) }
  const partsListSchema = { '@context': 'https://schema.org', '@type': 'ItemList', 'inLanguage': 'ms', name: 'Kategori Alat Ganti Massey Ferguson', description: 'Alat ganti traktor Massey Ferguson mengikut sistem — enjin Perkins, transmisi, hidraulik, stereng & gandar, elektrik, penapis & servis.', numberOfItems: PARTS.length, itemListElement: PARTS.map((cat, i) => ({ '@type': 'ListItem', position: i + 1, item: { '@type': 'Product', name: `Massey Ferguson ${cat.category}`, description: `${cat.items.join(', ')}` } })) }
  const speakableSchema = { '@context': 'https://schema.org', '@type': 'SpeakableSpecification', 'inLanguage': 'ms', xpath: ["/html/head/title", "/html/head/meta[@name='description']/@content"] }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(partsListSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(speakableSchema) }} />
      <WhatsappCTA label="ms-mf-sticky" message="Hi, saya perlukan alat ganti Massey Ferguson. Model traktor: ___ Alat ganti diperlukan: ___" className="fixed bottom-6 right-6 z-50 bg-green-500 hover:bg-green-600 text-white px-5 py-3.5 rounded-full shadow-2xl font-bold text-sm flex items-center gap-2 transition-all hover:scale-105"><MessageCircle className="w-5 h-5" /> WhatsApp Kami</WhatsappCTA>
      <div className="min-h-screen font-sans text-slate-900 antialiased">
        <nav className="bg-white shadow-sm sticky top-0 z-40">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
            <Link href="/ms" className="flex items-center"><span className="font-bold text-xl text-slate-900 tracking-tight">SourceSage</span><span className="text-blue-600 font-bold text-xl">.ai</span></Link>
            <div className="hidden md:flex gap-8 text-sm font-semibold text-slate-600">
              <Link href="/ms/#brands" className="hover:text-blue-600 transition-colors">Jenama</Link>
              <Link href="/ms/#marine" className="hover:text-blue-600 transition-colors">Marin</Link>
              <Link href="/ms/#how-it-works" className="hover:text-blue-600 transition-colors">Cara Kerja</Link>
              <Link href="/ms/about" className="hover:text-blue-600 transition-colors">Tentang</Link>
              <Link href="/ms/blog" className="hover:text-blue-600 transition-colors">Blog</Link>
              <Link href="/ms/#request" className="hover:text-blue-600 transition-colors">Minta Sebut Harga</Link>
            </div>
            <div className="flex items-center gap-2">
              <LangSwitcher currentLang="ms" />
              <WhatsappCTA label="ms-mf-navbar" message="Hi, saya perlukan alat ganti Massey Ferguson. Model traktor: ___ Alat ganti diperlukan: ___" className="bg-green-500 hover:bg-green-600 text-white px-4 py-2.5 rounded-lg font-bold transition-all text-sm flex items-center gap-2"><MessageCircle className="w-4 h-4" /> WhatsApp Kami</WhatsappCTA>
            </div>
          </div>
        </nav>
        <div className="bg-slate-50 border-b border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3 text-sm text-slate-500"><Link href="/ms" className="hover:text-blue-600 transition-colors">Laman Utama</Link><span className="mx-2">/</span><span className="text-slate-700 font-medium">Alat Ganti Massey Ferguson Malaysia</span></div></div>
        <header className="bg-white pt-16 pb-20 border-b border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-red-50 text-red-800 text-xs font-bold uppercase tracking-widest mb-6"><MapPin className="w-4 h-4 text-red-600" /> Traktor Berkuasa Perkins — Malaysia</div><h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 leading-tight mb-6">Alat Ganti Massey Ferguson Malaysia<br /><span className="text-blue-600">Alat Ganti Enjin Perkins. Sukar Dicari. Pantas Diperoleh.</span></h1><p className="text-xl text-slate-600 leading-relaxed mb-8">Kit overhaul, pam suntikan, pemasangan klac, seal hidraulik, dan alat ganti enjin Perkins untuk MF240, MF350, MF375, MF385 dan traktor MF klasik. Apabila pengedar AGCO tempatan tidak dapat membantu, kami mencarinya.</p><div className="flex flex-col sm:flex-row gap-4"><Link href="/ms/#request" className="px-8 py-4 text-lg font-bold rounded-xl text-white bg-blue-600 hover:bg-blue-700 shadow-xl shadow-blue-200 transition-all text-center flex items-center justify-center gap-2">Minta Alat Ganti MF <ChevronRight className="w-5 h-5" /></Link><WhatsappCTA label="ms-mf-hero" message="Hi, traktor Massey Ferguson saya perlukan alat ganti. Model: ___ Alat ganti diperlukan: ___" className="px-8 py-4 text-lg font-bold rounded-xl text-white bg-green-500 hover:bg-green-600 transition-all text-center flex items-center justify-center gap-2"><MessageCircle className="w-5 h-5" /> WhatsApp Sekarang</WhatsappCTA></div></div></div></header>
        <section className="py-20 bg-slate-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-sm font-black text-blue-600 uppercase tracking-[0.3em] mb-4">Model Yang Disokong</h2><h3 className="text-3xl font-bold text-slate-900">Traktor Massey Ferguson Yang Kami Bantu</h3><p className="mt-4 text-slate-600 max-w-2xl mx-auto">Dari MF240 yang meluas hingga model vintaj klasik — jika ia Massey Ferguson atau menggunakan enjin Perkins, kami boleh dapatkan alat gantinya.</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">{MODELS.map(m => (<div key={m.model} className="bg-white rounded-2xl p-6 border border-slate-200 hover:border-blue-200 hover:shadow-md transition-all"><h4 className="text-xl font-bold text-slate-900 mb-1">{m.model}</h4><p className="text-xs font-semibold text-blue-600 mb-3">{m.engine}</p><p className="text-sm text-slate-500">{m.note}</p></div>))}</div><div className="mt-8 text-center"><p className="text-slate-500 text-sm mb-3">Tidak nampak model anda?</p><WhatsappCTA label="ms-mf-model-unlisted" message="Hi, saya perlukan alat ganti untuk traktor Massey Ferguson saya. Model: ___ Tahun: ___ Alat ganti diperlukan: ___" className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-xl font-bold text-sm transition-all"><MessageCircle className="w-4 h-4" /> Tanya Tentang Model Anda</WhatsappCTA></div></div></section>
        <section className="py-16 bg-amber-50 border-y border-amber-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-start gap-5 max-w-3xl mx-auto"><Wrench className="w-8 h-8 text-amber-600 shrink-0 mt-1" /><div><h2 className="text-xl font-bold text-slate-900 mb-3">Ini Sebenarnya Masalah Alat Ganti Perkins</h2><p className="text-slate-600 leading-relaxed mb-3">Kebanyakan traktor Massey Ferguson di Malaysia menggunakan enjin Perkins — AD3.152, A4.248, atau AD4.203. Enjin ini dibina dengan baik dengan pasaran aftermarket global yang besar, tetapi saluran alat ganti Perkins sah di Malaysia adalah nipis di luar pengedar industri.</p><p className="text-slate-600 leading-relaxed">Kami mendapatkan alat ganti enjin Perkins melalui saluran dari UK, buatan India, dan OEM. Kedua-dua komponen sisi traktor (klac, hidraulik, gandar) dan dalaman enjin Perkins adalah dalam skop kami.</p></div></div></div></section>
        <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-sm font-black text-blue-600 uppercase tracking-[0.3em] mb-4">Katalog Alat Ganti</h2><h3 className="text-3xl font-bold text-slate-900">Apa Yang Kami Peroleh untuk Massey Ferguson</h3></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{PARTS.map(cat => (<div key={cat.category} className="bg-slate-50 rounded-2xl p-6 border border-slate-100"><h4 className="font-bold text-slate-800 text-sm uppercase tracking-wide mb-4 flex items-center gap-2"><Wrench className="w-4 h-4 text-blue-500" /> {cat.category}</h4><ul className="space-y-2">{cat.items.map(item => (<li key={item} className="flex items-center gap-2 text-sm text-slate-600"><CheckCircle className="w-3.5 h-3.5 text-green-500 shrink-0" /> {item}</li>))}</ul></div>))}</div></div></section>
        <section className="py-20 bg-slate-900 text-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl font-bold">Kenapa Bengkel Pilih SourceSage untuk Alat Ganti MF</h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{[{icon: <ShieldCheck className="w-6 h-6 text-blue-400" />, title: 'Kepakaran Model Klasik', body: 'MF135 dan MF240 sudah berdekad lamanya. Kami tahu varian enjin Perkins yang dipasang pada model MF pasaran eksport yang berbeza, dan kit aftermarket mana yang benar-benar serasi berbanding yang salah dilabel.'},{icon: <AlertTriangle className="w-6 h-6 text-amber-400" />, title: 'Keutamaan Kerosakan', body: 'Traktor yang rosak semasa penanaman atau penuaian kos lebih daripada alat ganti. Kami memberi keutamaan kepada kes kerosakan segera, menawarkan pilihan penghantaran udara jika perlu, dan memberikan ETA yang tepat — bukan "check balik minggu depan."'},{icon: <MapPin className="w-6 h-6 text-green-400" />, title: 'Penghantaran Seluruh Malaysia', body: 'Semenanjung dan Malaysia Timur dilindungi. Kurier berpenjejak dengan kemas kini WhatsApp. Alat ganti dari UK atau India tiba dalam 7–14 hari bekerja; alat ganti stok tempatan dihantar hari yang sama atau esok.'}].map(card => (<div key={card.title} className="bg-slate-800 rounded-2xl p-8 border border-slate-700"><div className="w-12 h-12 bg-slate-700 rounded-xl flex items-center justify-center mb-5">{card.icon}</div><h3 className="font-bold text-white text-lg mb-3">{card.title}</h3><p className="text-slate-300 leading-relaxed">{card.body}</p></div>))}</div></div></section>
        <section className="py-20 bg-slate-50 border-t border-slate-100"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl font-bold text-slate-900">Soalan Lazim</h2></div><div className="space-y-6">{FAQS.map(faq => (<div key={faq.q} className="bg-white rounded-2xl p-7 border border-slate-200"><h3 className="font-bold text-slate-900 mb-3">{faq.q}</h3><p className="text-slate-600 leading-relaxed">{faq.a}</p></div>))}</div></div></section>
        <section className="py-20 bg-blue-600 text-white"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl font-bold mb-4">Perlukan Alat Ganti Massey Ferguson Sekarang?</h2><p className="text-blue-100 text-lg mb-8">Beritahu kami model traktor dan apa yang anda perlukan. Kami akan sahkan ketersediaan dan harga — biasanya dalam 24 jam.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/ms/#request" className="px-8 py-4 text-lg font-bold rounded-xl bg-white text-blue-700 hover:bg-blue-50 transition-all text-center">Hantar Permintaan Alat Ganti</Link><WhatsappCTA label="ms-mf-final-cta" message="Hi, saya perlukan alat ganti Massey Ferguson segera. Model: ___ Alat ganti diperlukan: ___" className="px-8 py-4 text-lg font-bold rounded-xl bg-green-500 hover:bg-green-600 text-white transition-all flex items-center justify-center gap-2"><MessageCircle className="w-5 h-5" /> WhatsApp Pasukan Kami</WhatsappCTA></div></div></section>
        <footer className="bg-white py-12 text-slate-500 border-t border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex flex-col md:flex-row justify-between items-center gap-6 mb-8"><div><span className="font-black text-xl tracking-tighter text-slate-900">SourceSage</span><span className="font-black text-xl text-blue-600">.ai</span><p className="text-sm text-slate-500 mt-1">Ipoh, Perak — Pakar Perolehan Alat Ganti di Malaysia</p></div><div className="flex gap-6 text-sm font-semibold"><a href="mailto:info@sourcesage.ai" className="hover:text-blue-600 flex items-center gap-2 transition-colors"><Mail className="w-4 h-4" /> info@sourcesage.ai</a><WhatsappCTA label="ms-mf-footer" message="Hi, saya perlukan alat ganti Massey Ferguson. Model traktor: ___ Alat ganti diperlukan: ___" className="hover:text-green-600 flex items-center gap-2 transition-colors"><MessageCircle className="w-4 h-4" /> WhatsApp</WhatsappCTA></div></div><div className="text-center pt-6 border-t border-slate-100"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400">© 2026 SourceSage.ai. Perolehan Alat Ganti Pertanian &amp; Marin, Malaysia.</p></div></div></footer>
      </div>
    </>
  )
}
