import Link from 'next/link'
import { MessageCircle, Mail, CheckCircle, Wrench, AlertTriangle, MapPin, ChevronRight, ShieldCheck } from 'lucide-react'
import WhatsappCTA from '../../../components/WhatsappCTA'
import LangSwitcher from '../../../components/LangSwitcher'

export const metadata = {
  title: 'Alat Ganti Zoomlion Malaysia — Perolehan Peralatan Berat | SourceSage',
  description: 'Pembekal alat ganti Zoomlion Malaysia. Alat ganti undercarriage, kelengkapan hidraulik, komponen enjin. Perolehan pantas untuk mesin pertanian & pembinaan Zoomlion.',
  alternates: { canonical: '/ms/zoomlion-parts-malaysia/', languages: { 'en': 'https://sourcesage.ai/zoomlion-parts-malaysia/', 'ms': 'https://sourcesage.ai/ms/zoomlion-parts-malaysia/', 'zh-Hans': 'https://sourcesage.ai/zh/zoomlion-parts-malaysia/', 'x-default': 'https://sourcesage.ai/zoomlion-parts-malaysia/' } },
  openGraph: {
    title: 'Alat Ganti Zoomlion Malaysia — Perolehan Peralatan Berat | SourceSage',
    description: 'Pembekal alat ganti Zoomlion Malaysia. Alat ganti undercarriage, kelengkapan hidraulik, komponen enjin. Perolehan pantas untuk mesin pertanian & pembinaan Zoomlion.',
    url: 'https://sourcesage.ai/ms/zoomlion-parts-malaysia/',
    siteName: 'SourceSage.ai', type: 'website', locale: 'ms_MY',
    images: [{ url: 'https://sourcesage.ai/images/og-home.png', width: 1200, height: 630, alt: 'Alat Ganti Zoomlion Malaysia — SourceSage' }],
  },
  twitter: { card: 'summary_large_image', title: 'Alat Ganti Zoomlion Malaysia — Perolehan Peralatan Berat | SourceSage', description: 'Pembekal alat ganti Zoomlion Malaysia. Alat ganti undercarriage, kelengkapan hidraulik, komponen enjin.', images: ['https://sourcesage.ai/images/og-home.png'] },
}

const MACHINES = [
  { model: 'Zoomlion Siri RC', type: 'Mesin penuai padi', detail: 'RC50, RC60, RC70 — meluas digunakan di kawasan padi Kedah & Kelantan' },
  { model: 'Zoomlion Siri ZP', type: 'Penanam padi', detail: 'ZP4, ZP6 — popular di skim padi Semenanjung' },
  { model: 'Zoomlion Siri 4LZ', type: 'Penuai kecil', detail: '4LZ-1.0, 4LZ-1.5 — mesin pekebun kecil baris tunggal' },
  { model: 'Zoomlion Crawler Crane', type: 'Pembinaan', detail: 'Siri ZCC — digunakan dalam projek ladang & infrastruktur' },
  { model: 'Zoomlion Pam Konkrit', type: 'Pembinaan', detail: 'Siri HBT & ZLJ — tapak pembinaan di seluruh negara' },
  { model: 'Zoomlion Kren Menara', type: 'Pembinaan', detail: 'Siri ZTT & ZT — pembinaan bangunan tinggi' },
]

const PARTS = [
  { category: 'Penuai Padi', items: ['Mata pemotong & bar pemotong', 'Gendang perontok & cekung', 'Rantai lif bijirin', 'Set tali sawat transmisi', 'Aci pemacu header'] },
  { category: 'Enjin & Pemacu', items: ['Set gasket enjin diesel', 'Penyuntik bahan api & pam', 'Alternator & penghidup', 'Pam hidraulik & motor', 'Seal kotak gear pacuan akhir'] },
  { category: 'Penanam Padi', items: ['Garpu penanaman & pick-up', 'Kasut apungan & skid', 'Rolon suapan tikar anak benih', 'Rantai pemacu & sproket', 'Cam penanaman'] },
  { category: 'Penapis & Alat Pakai', items: ['Elemen penapis udara', 'Penapis balik hidraulik', 'Kartrij penapis minyak', 'Penapis awal bahan api', 'Hos & pengapit penyejuk'] },
  { category: 'Undercarriage', items: ['Jejak getah & jejak keluli', 'Penunggang & rolon pembawa', 'Sproket pemacu', 'Penegang jejak', 'Roda bogie'] },
  { category: 'Elektrik & Kawalan', items: ['Unit paparan papan pemuka', 'Sensor penuaian', 'Injap solenoid', 'Abah-abah pendawaian', 'Kotak geganti & fius'] },
]

const FAQS = [
  { q: 'Kenapa alat ganti Zoomlion sukar ditemui di Malaysia?', a: 'Zoomlion adalah pengeluar China dengan kehadiran pengedar sah yang terhad di luar kawasan padi Semenanjung. Banyak mesin diimport oleh pedagang individu daripada pengedar rasmi, jadi alat ganti tidak pernah memasuki rantaian bekalan normal. Kami mendapatkan terus dari China dan dari pengedar sekunder yang menyimpan komponen serasi Zoomlion.' },
  { q: 'Berapa lama masa untuk mendapatkan alat ganti Zoomlion?', a: 'Alat ganti yang tersedia di Malaysia dihantar dalam 1–2 hari. Alat ganti yang diperoleh terus dari China biasanya mengambil 7–14 hari bekerja melalui penghantaran udara. Untuk situasi mesin rosak segera, kami menggunakan penghantaran ekspres dan memberikan ETA yang pasti sebelum anda komited.' },
  { q: 'Adakah anda membekalkan alat ganti OEM Zoomlion atau aftermarket?', a: 'Kedua-duanya. Alat ganti OEM datang dengan nombor alat ganti Zoomlion dan kebolehkesanan. Untuk barang haus tinggi (mata pisau, tali sawat, rantai) alternatif aftermarket berkualiti tersedia dan selalunya 40–60% lebih murah. Kami melabel dengan jelas supaya anda boleh membuat keputusan.' },
  { q: 'Bolehkah anda bantu jika saya hanya ada model mesin, bukan nombor alat ganti?', a: 'Ya. Hantarkan model mesin, tahun, dan penerangan atau gambar alat ganti. Pasukan kami merujuk silang terhadap gambar rajah alat ganti Zoomlion untuk mengenal pasti komponen yang betul sebelum memesan.' },
  { q: 'Adakah anda meliputi peralatan pembinaan Zoomlion serta mesin pertanian?', a: 'Ya — kedua-dua pertanian (mesin penuai, penanam) dan pembinaan (kren crawler, pam konkrit, kren menara) adalah dalam skop. Syarikat ladang yang mengendalikan kedua-dua jenis peralatan adalah pelanggan utama kami.' },
]

export default function MsZoomlionPage() {
  const serviceSchema = { '@context': 'https://schema.org', '@type': 'Service', 'inLanguage': 'ms', name: 'Perolehan Alat Ganti Zoomlion Malaysia', provider: { '@type': 'LocalBusiness', name: 'SourceSage.ai', url: 'https://sourcesage.ai', areaServed: { '@type': 'Country', name: 'Malaysia' } }, description: 'Perolehan alat ganti peralatan pertanian dan pembinaan Zoomlion sukar dicari di seluruh Malaysia.', serviceType: 'Perolehan Alat Ganti', areaServed: [{ '@type': 'State', name: 'Kedah' }, { '@type': 'State', name: 'Kelantan' }, { '@type': 'State', name: 'Perak' }, { '@type': 'State', name: 'Selangor' }, { '@type': 'State', name: 'Sabah' }, { '@type': 'State', name: 'Sarawak' }] }
  const breadcrumbSchema = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', 'inLanguage': 'ms', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Laman Utama', item: 'https://sourcesage.ai/ms/' }, { '@type': 'ListItem', position: 2, name: 'Alat Ganti Zoomlion Malaysia', item: 'https://sourcesage.ai/ms/zoomlion-parts-malaysia' }] }
  const faqSchema = { '@context': 'https://schema.org', '@type': 'FAQPage', 'inLanguage': 'ms', mainEntity: FAQS.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) }
  const partsListSchema = { '@context': 'https://schema.org', '@type': 'ItemList', 'inLanguage': 'ms', name: 'Kategori Alat Ganti Zoomlion', description: 'Alat ganti Zoomlion mengikut kategori — penuai padi, enjin & pemacu, penanam padi, penapis & alat pakai, undercarriage, elektrik & kawalan.', numberOfItems: PARTS.length, itemListElement: PARTS.map((cat, i) => ({ '@type': 'ListItem', position: i + 1, item: { '@type': 'Product', name: `Zoomlion ${cat.category}`, description: `${cat.items.join(', ')}` } })) }
  const speakableSchema = { '@context': 'https://schema.org', '@type': 'SpeakableSpecification', 'inLanguage': 'ms', xpath: ["/html/head/title", "/html/head/meta[@name='description']/@content"] }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(partsListSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(speakableSchema) }} />
      <WhatsappCTA label="ms-zl-sticky" message="Hi, saya perlukan alat ganti Zoomlion. Model mesin: ___ Alat ganti diperlukan: ___" className="fixed bottom-6 right-6 z-50 bg-green-500 hover:bg-green-600 text-white px-5 py-3.5 rounded-full shadow-2xl font-bold text-sm flex items-center gap-2 transition-all hover:scale-105"><MessageCircle className="w-5 h-5" /> WhatsApp Kami</WhatsappCTA>
      <div className="min-h-screen font-sans text-slate-900 antialiased">
        <nav className="bg-white shadow-sm sticky top-0 z-40">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
            <Link href="/ms" className="flex items-center"><span className="font-bold text-xl text-slate-900 tracking-tight">SourceSage</span><span className="text-blue-600 font-bold text-xl">.ai</span></Link>
            <div className="hidden md:flex gap-8 text-sm font-semibold text-slate-600">
              <Link href="/ms/#brands" className="hover:text-blue-600 transition-colors">Jenama</Link>
              <Link href="/ms/#marine" className="hover:text-blue-600 transition-colors">Marin</Link>
              <Link href="/ms/#how-it-works" className="hover:text-blue-600 transition-colors">Cara Kerja</Link>
              <Link href="/ms/about" className="hover:text-blue-600 transition-colors">Tentang</Link>
              <Link href="/ms/blog" className="hover:text-blue-600 transition-colors">Blog</Link>
              <Link href="/ms/#request" className="hover:text-blue-600 transition-colors">Minta Sebut Harga</Link>
            </div>
            <div className="flex items-center gap-2">
              <WhatsappCTA label="ms-zl-navbar" message="Hi, saya perlukan alat ganti Zoomlion. Model mesin: ___ Alat ganti diperlukan: ___" className="bg-green-500 hover:bg-green-600 text-white px-4 py-2.5 rounded-lg font-bold transition-all text-sm flex items-center gap-2"><MessageCircle className="w-4 h-4" /> WhatsApp Kami</WhatsappCTA>
              <LangSwitcher currentLang="ms" />
            </div>
          </div>
        </nav>
        <div className="bg-slate-50 border-b border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3 text-sm text-slate-500"><Link href="/ms" className="hover:text-blue-600 transition-colors">Laman Utama</Link><span className="mx-2">/</span><span className="text-slate-700 font-medium">Alat Ganti Zoomlion Malaysia</span></div></div>
        <header className="bg-white pt-16 pb-20 border-b border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-green-50 text-green-800 text-xs font-bold uppercase tracking-widest mb-6"><MapPin className="w-4 h-4 text-green-600" /> Peralatan Pertanian &amp; Pembinaan</div><h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 leading-tight mb-6">Alat Ganti Zoomlion Malaysia<br /><span className="text-blue-600">Apabila Pengedar Tidak Dapat Bantu. Kami Boleh.</span></h1><p className="text-xl text-slate-600 leading-relaxed mb-8">Mata pisau penuai padi, pick-up penanam, seal hidraulik, alat ganti enjin dan komponen elektrik untuk mesin pertanian dan pembinaan Zoomlion. Diperoleh dari China dan pengedar sekunder tempatan — pantas.</p><div className="flex flex-col sm:flex-row gap-4"><Link href="/ms/#request" className="px-8 py-4 text-lg font-bold rounded-xl text-white bg-blue-600 hover:bg-blue-700 shadow-xl shadow-blue-200 transition-all text-center flex items-center justify-center gap-2">Minta Alat Ganti Zoomlion <ChevronRight className="w-5 h-5" /></Link><WhatsappCTA label="ms-zl-hero" message="Hi, mesin Zoomlion saya rosak. Model mesin: ___ Alat ganti diperlukan: ___ Lokasi: ___" className="px-8 py-4 text-lg font-bold rounded-xl text-white bg-green-500 hover:bg-green-600 transition-all text-center flex items-center justify-center gap-2"><MessageCircle className="w-5 h-5" /> WhatsApp Sekarang</WhatsappCTA></div></div></div></header>
        <section className="py-16 bg-amber-50 border-y border-amber-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-start gap-5 max-w-3xl mx-auto"><AlertTriangle className="w-8 h-8 text-amber-500 shrink-0 mt-1" /><div><h2 className="text-xl font-bold text-slate-900 mb-3">Masalah Alat Ganti Zoomlion di Malaysia</h2><p className="text-slate-600 leading-relaxed mb-3">Zoomlion memasuki Malaysia terutamanya melalui pengimport kecil dan skim kerajaan pertanian daripada melalui rangkaian pengedar sah. Ini bermaksud tiada depot alat ganti rasmi, tiada stok terjamin, dan masa menunggu lama apabila mesin penuai anda rosak di pertengahan musim.</p><p className="text-slate-600 leading-relaxed">Kami memintas jurang ini dengan mendapatkan terus dari pembekal yang diluluskan Zoomlion di China dan dari pengedar sekunder yang mantap. Kebanyakan pertanyaan alat ganti mendapat kemas kini ketersediaan dalam 24 jam.</p></div></div></div></section>
        <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-sm font-black text-blue-600 uppercase tracking-[0.3em] mb-4">Julat Peralatan</h2><h3 className="text-3xl font-bold text-slate-900">Mesin Zoomlion Yang Kami Liput</h3></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">{MACHINES.map(m => (<div key={m.model} className="bg-slate-50 rounded-2xl p-6 border border-slate-200 hover:border-blue-200 hover:shadow-md transition-all"><p className="text-xs font-black text-blue-600 uppercase tracking-widest mb-1">{m.type}</p><h4 className="text-lg font-bold text-slate-900 mb-2">{m.model}</h4><p className="text-sm text-slate-500">{m.detail}</p></div>))}</div><div className="mt-6 text-center"><p className="text-slate-500 text-sm mb-3">Tidak nampak model anda?</p><WhatsappCTA label="ms-zl-model-unlisted" message="Hi, saya perlukan alat ganti untuk mesin Zoomlion saya. Model: ___ Tahun: ___ Alat ganti diperlukan: ___" className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-xl font-bold text-sm transition-all"><MessageCircle className="w-4 h-4" /> Tanya Tentang Model Anda</WhatsappCTA></div></div></section>
        <section className="py-20 bg-slate-50 border-t border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-sm font-black text-blue-600 uppercase tracking-[0.3em] mb-4">Katalog Alat Ganti</h2><h3 className="text-3xl font-bold text-slate-900">Apa Yang Kami Peroleh untuk Zoomlion</h3></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">{PARTS.map(cat => (<div key={cat.category} className="bg-white rounded-2xl p-6 border border-slate-200"><h4 className="font-bold text-slate-800 text-sm uppercase tracking-wide mb-4 flex items-center gap-2"><Wrench className="w-4 h-4 text-blue-500" /> {cat.category}</h4><ul className="space-y-2">{cat.items.map(item => (<li key={item} className="flex items-center gap-2 text-sm text-slate-600"><CheckCircle className="w-3.5 h-3.5 text-green-500 shrink-0" /> {item}</li>))}</ul></div>))}</div></div></section>
        <section className="py-20 bg-slate-900 text-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 lg:grid lg:grid-cols-2 lg:gap-16 items-center"><div><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-amber-900/50 text-amber-300 text-xs font-bold uppercase tracking-widest mb-6"><AlertTriangle className="w-4 h-4" /> Keutamaan Musim Tuai</div><h2 className="text-3xl font-bold mb-6">Penuai Rosak Semasa Musim Tuai Kos Lebih Daripada Alat Ganti</h2><p className="text-slate-300 text-lg leading-relaxed mb-6">Tetingkap tuaian padi di Malaysia — terutama di Kedah, Kelantan, dan Sekinchan — adalah ketat. Penuai yang rosak selama 3 hari menunggu mata pemotong atau tali sawat perontok boleh merugikan ribuan ringgit dalam kehilangan padi.</p><p className="text-slate-300 leading-relaxed mb-8">Kami mengendalikan kes mesin rosak sebagai kecemasan. WhatsApp kami dengan model dan kerosakan, dan kami akan memberikan garis masa perolehan dalam beberapa jam. Penghantaran udara dari China tersedia untuk alat ganti kritikal.</p><WhatsappCTA label="ms-zl-harvest-emergency" message="Hi, mesin penuai Zoomlion saya ROSAK semasa musim tuai! Model mesin: ___ Kerosakan/Alat ganti diperlukan: ___ Lokasi: ___" className="inline-flex items-center gap-2 bg-green-500 hover:bg-green-600 text-white px-6 py-3.5 rounded-xl font-bold transition-all"><MessageCircle className="w-5 h-5" /> WhatsApp Kecemasan — Mesin Rosak</WhatsappCTA></div><div className="mt-12 lg:mt-0 grid grid-cols-2 gap-4">{[{region: 'Kedah', note: 'Padi dua musim — Skim Muda'},{region: 'Kelantan', note: 'Padi satu musim & tanaman campuran'},{region: 'Sekinchan', note: 'Kawasan padi Selangor'},{region: 'Perak', note: 'Skim Pengairan Kerian'},{region: 'Sabah', note: 'Pertanian campuran & ladang'},{region: 'Sarawak', note: 'Padi & padi tanah tinggi'}].map(r => (<div key={r.region} className="bg-slate-800 rounded-xl p-4 border border-slate-700"><p className="font-bold text-white text-sm mb-1">{r.region}</p><p className="text-slate-400 text-xs">{r.note}</p></div>))}</div></div></section>
        <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h3 className="text-3xl font-bold text-slate-900">Kenapa Petani & Kontraktor Pilih SourceSage</h3></div><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{[{icon: <MapPin className="w-6 h-6 text-green-500" />, title: 'Perolehan Terus China', body: 'Kami mempunyai hubungan mantap dengan pembekal alat ganti yang diluluskan Zoomlion di China. Tiada orang tengah menaikkan harga — dan kami berkongsi nombor alat ganti penuh dan kebolehkesanan dengan setiap pesanan.'},{icon: <AlertTriangle className="w-6 h-6 text-amber-500" />, title: 'Triage Mesin Rosak', body: 'Mesin rosak semasa musim diberi keutamaan sebagai kecemasan. Kami mengutamakan kes anda, menawarkan pilihan penghantaran udara jika penghantaran laut terlalu lambat, dan memberikan ETA yang pasti — bukan "kami akan cuba sedaya upaya."'},{icon: <ShieldCheck className="w-6 h-6 text-blue-500" />, title: 'Pengenalan Teknikal', body: 'Tiada nombor alat ganti? Tiada masalah. Hantar gambar alat ganti yang rosak atau plat mesin. Pasukan kami merujuk silang terhadap gambar rajah alat ganti Zoomlion untuk mencari komponen yang betul.'}].map(card => (<div key={card.title} className="bg-slate-50 rounded-2xl p-8 border border-slate-100"><div className="w-12 h-12 bg-white rounded-xl border border-slate-200 flex items-center justify-center mb-5 shadow-sm">{card.icon}</div><h3 className="font-bold text-slate-900 text-lg mb-3">{card.title}</h3><p className="text-slate-600 leading-relaxed">{card.body}</p></div>))}</div></div></section>
        <section className="py-20 bg-slate-50 border-t border-slate-100"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center mb-12"><h2 className="text-3xl font-bold text-slate-900">Soalan Lazim</h2></div><div className="space-y-6">{FAQS.map(faq => (<div key={faq.q} className="bg-white rounded-2xl p-7 border border-slate-200"><h3 className="font-bold text-slate-900 mb-3">{faq.q}</h3><p className="text-slate-600 leading-relaxed">{faq.a}</p></div>))}</div></div></section>
        <section className="py-20 bg-blue-600 text-white"><div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center"><h2 className="text-3xl font-bold mb-4">Perlukan Alat Ganti Zoomlion Sekarang?</h2><p className="text-blue-100 text-lg mb-8">Beritahu kami model mesin dan alat ganti yang anda perlukan. Kami akan sahkan ketersediaan dan harga — biasanya dalam 24 jam.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><Link href="/ms/#request" className="px-8 py-4 text-lg font-bold rounded-xl bg-white text-blue-700 hover:bg-blue-50 transition-all text-center">Hantar Permintaan Alat Ganti</Link><WhatsappCTA label="ms-zl-final-cta" message="Hi, saya perlukan alat ganti Zoomlion segera. Model mesin: ___ Alat ganti diperlukan: ___ Lokasi: ___" className="px-8 py-4 text-lg font-bold rounded-xl bg-green-500 hover:bg-green-600 text-white transition-all flex items-center justify-center gap-2"><MessageCircle className="w-5 h-5" /> WhatsApp Pasukan Kami</WhatsappCTA></div></div></section>
        <footer className="bg-white py-12 text-slate-500 border-t border-slate-100"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex flex-col md:flex-row justify-between items-center gap-6 mb-8"><div><span className="font-black text-xl tracking-tighter text-slate-900">SourceSage</span><span className="font-black text-xl text-blue-600">.ai</span><p className="text-sm text-slate-500 mt-1">Ipoh, Perak — Pakar Perolehan Alat Ganti di Malaysia</p></div><div className="flex gap-6 text-sm font-semibold"><a href="mailto:info@sourcesage.ai" className="hover:text-blue-600 flex items-center gap-2 transition-colors"><Mail className="w-4 h-4" /> info@sourcesage.ai</a><WhatsappCTA label="ms-zl-footer" message="Hi, saya perlukan alat ganti Zoomlion. Model mesin: ___ Alat ganti diperlukan: ___" className="hover:text-green-600 flex items-center gap-2 transition-colors"><MessageCircle className="w-4 h-4" /> WhatsApp</WhatsappCTA></div></div><div className="text-center pt-6 border-t border-slate-100"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-400">© 2026 SourceSage.ai. Perolehan Alat Ganti Pertanian &amp; Marin, Malaysia.</p></div></div></footer>
      </div>
    </>
  )
}
